development:
  adapter: async

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
      # 読み込み用のデータベースも指定する場合は次のようにする
      # reading: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
