default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: qa2_chatbot_app_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: qa2_chatbot_app_test

production:
  <<: *default
  adapter: postgresql
  host: your-db-host.render.com
  database: qa2_chatbot_app_production
  username: your_db_username
  password: your_db_password
