default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: qa2_chatbot_app_development
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: qa2_chatbot_app_test
  username: root
  password:
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

solid_cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
