default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: qa2_chatbot_app_development

test:
  <<: *default
  database: qa2_chatbot_app_test

production:
  <<: *default
  database: furima42061
  username: furima42061_user
  password: <%= ENV["DB_PASSWORD"] %>
  host: dpg-d1rod6ur433s73aj7ot0-a
  port: 5432

cable:
  <<: *production

queue:
  <<: *production
